AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys the roles needed for SRAVerify to run in each account.
Parameters:
  SRAVerifyAccountID:
    Description: 'Specifies the account ID where SRAVerify will run from.'
    Type: String
    Default: '012345678910'
    AllowedPattern: \d{12}
    ConstraintDescription: Enter the 12 digit account ID with no spaces.

Resources:
  SRAMemberRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Resource has an explicit name so SRAVerify can loop through and assume it in each account.
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SRAMemberRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${SRAVerifyAccountID}:root'
            Action:
              - 'sts:AssumeRole'
            Condition:
              ArnEquals:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${SRAVerifyAccountID}:role/SRAVerifyCodeBuildServiceRole
      ManagedPolicyArns:
        - !Ref SRAVerifyLeastPrivilege
        - !Ref SRAVerifyCheckPermissions

  SRAVerifyCheckPermissions:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Resource has an explicit name for documentation.
          - id: W13
            reason: SRA Verify needs read only * resource to evaluate configuration against SRA best practices.
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SRAVerifyCheckPermissions
      Description: Permissions for actions in check.py
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AccountPermissions
            Effect: Allow
            Action:
              - account:GetAccountInformation
            Resource: '*'

  # This policy is automatically generated from generate_iam_policy.py by extracting the boto3 calls used.
  SRAVerifyLeastPrivilege:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Policy is automatically generated from generate_iam_policy.py
          - id: W13
            reason: SRA Verify needs read only * resource to evaluate configuration against SRA best practices.
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SRAVerifyLeastPrivilege
      Description: Least privilege policy for SRA Verify tool
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3Permissions
            Effect: Allow
            Action:
              - s3:GetAccountPublicAccessBlock
              - s3:GetBucketLocation
              - s3:GetBucketPolicy
            Resource: '*'
          - Sid: Macie2Permissions
            Effect: Allow
            Action:
              - macie2:DescribeOrganizationConfiguration
              - macie2:GetAdministratorAccount
              - macie2:GetClassificationExportConfiguration
              - macie2:GetFindingsPublicationConfiguration
              - macie2:ListMembers
            Resource: '*'
          - Sid: OrganizationsPermissions
            Effect: Allow
            Action:
              - organizations:DescribeOrganization
              - organizations:ListAccounts
              - organizations:ListDelegatedAdministrators
            Resource: '*'
          - Sid: ConfigPermissions
            Effect: Allow
            Action:
              - config:DescribeConfigurationAggregatorSourcesStatus
              - config:DescribeConfigurationAggregators
              - config:DescribeConfigurationRecorderStatus
              - config:DescribeConfigurationRecorders
              - config:DescribeDeliveryChannelStatus
              - config:DescribeDeliveryChannels
            Resource: '*'
          - Sid: Inspector2Permissions
            Effect: Allow
            Action:
              - inspector2:BatchGetAccountStatus
              - inspector2:DescribeOrganizationConfiguration
              - inspector2:GetDelegatedAdminAccount
            Resource: '*'
          - Sid: AccessanalyzerPermissions
            Effect: Allow
            Action:
              - access-analyzer:GetAnalyzer
              - access-analyzer:ListAnalyzers
            Resource: '*'
          - Sid: CloudtrailPermissions
            Effect: Allow
            Action:
              - cloudtrail:DescribeTrails
              - cloudtrail:GetTrailStatus
            Resource: '*'
          - Sid: GuarddutyPermissions
            Effect: Allow
            Action:
              - guardduty:DescribeOrganizationConfiguration
              - guardduty:GetDetector
              - guardduty:ListDetectors
              - guardduty:ListOrganizationAdminAccounts
            Resource: '*'
          - Sid: SecurityhubPermissions
            Effect: Allow
            Action:
              - securityhub:DescribeOrganizationConfiguration
              - securityhub:GetAdministratorAccount
              - securityhub:GetEnabledStandards
              - securityhub:ListEnabledProductsForImport
              - securityhub:ListMembers
              - securityhub:ListOrganizationAdminAccounts
            Resource: '*'
          - Sid: Ec2Permissions
            Effect: Allow
            Action:
              - ec2:GetEbsEncryptionByDefault
            Resource: '*'
          - Sid: ShieldPermissions
            Effect: Allow
            Action:
              - shield:DescribeDrtAccess
              - shield:DescribeSubscription
              - shield:GetSubscriptionState
              - shield:ListProtections
            Resource: '*'
          - Sid: LambdaPermissions
            Effect: Allow
            Action:
              - lambda:GetFunction
            Resource: '*'
          - Sid: CloudfrontPermissions
            Effect: Allow
            Action:
              - cloudfront:GetDistributionConfig
            Resource: '*'
          - Sid: Wafv2Permissions
            Effect: Allow
            Action:
              - wafv2:GetWebAclForResource
              - wafv2:GetWebAcl
            Resource: '*'
          - Sid: StsPermissions
            Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: '*'
          - Sid: CloudwatchPermissions
            Effect: Allow
            Action:
              - cloudwatch:DescribeAlarmsForMetric
            Resource: '*'
