AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys the roles needed for SRAVerify to run in each account.
Parameters:
  SRAVerifyAccountID:
    Description: 'Specifies the account ID where SRAVerify will run from.'
    Type: String
    Default: '012345678910'
    AllowedPattern: \d{12}
    ConstraintDescription: Enter the 12 digit account ID with no spaces.

Resources:
  SRAMemberRole:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Role allows * in resource policy. The role needs broad, read-only privileges to review all resources. Only the CodeBuild role created as part of this solution can assume this role.
          - id: W28
            reason: Resource has an explicit name so SRAVerify can loop through and assume it in each account.
          - id: W76
            reason: SPCM for IAM policy is higher than 25 due to managed polices, and additional polices. Each section of the role has a comment with the SRAVerify documentation describing the need for the privileges. 
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: SRAMemberRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${SRAVerifyAccountID}:root' 
            Action:
              - 'sts:AssumeRole'
            Condition:
              ArnEquals:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${SRAVerifyAccountID}:role/SRAVerifyCodeBuildServiceRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/SecurityAudit'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/job-function/ViewOnlyAccess'